### ISSUE TITLE
GDI+ issue when downloading pictures for meetup events with special characters

### ISSUE THREAD

**Issue by Thohean** [krcourville/meetup-photo-download#20]
I'm getting the generic GDI+ error when I try to download pictures from events that have special characters in the names. Events with characters like *** and !!! can't download, because the folder can't contain those characters, so when the program looks for the folder, it can't find it.

**Comment by krcourville** [comment]
Hello,

Thank you for your interest in MPDL!

I can no longer support this project as open source.  This issue has been addressed in [Easy Photo Downloader](https://easydownload.photos/).  

For further assistance, please use the feedback mechanisms provided at [Easy Photo Downloader](https://easydownload.photos/).
