### ISSUE TITLE
can't run .exe file

### ISSUE THREAD

**Issue by roxyad** [krcourville/meetup-photo-download#21]
HI I tried downloading this program, when I try to run the .exe file I get an error message
"meetup photo downloader has stopped working"
I have windows 10
is anyone able to help me? cheers

**Comment by shtefanntz** [comment]
Try recompiling the solution from the trunk folder. 
The code is still valid and works with the meetup.com API.

**Comment by krcourville** [comment]
Hello,

Thank you for your interest in MPDL!

I can no longer support this project as open source.  This issue has been addressed in [Easy Photo Downloader](https://easydownload.photos/).  

For further assistance, please use the feedback mechanisms provided at [Easy Photo Downloader](https://easydownload.photos/).
