### ISSUE TITLE
unable to pull more then 200 albums? Would love to fix this in the code for myself just need help were to find it.

### ISSUE THREAD

**Issue by pupshadow** [krcourville/meetup-photo-download#22]
Hello I would first off like to say your program here has helped me alot with headaches of having to retrieve photos from my group.

I would like to ask were in the code did you put the time out of it pulling 200 albums because i would love to edit it myself so i could get the rest of my photos. 

200 albums is about 10 pages on meetup i have 30 pages i need to go though if you are able to help i would like to donate to you for making a program that helps people download photos off this site.

thank you if you are able to help and hope to hear from you shortly.

Best Michael

**Comment by krcourville** [comment]
Hello,

Thank you for your interest in MPDL!

I can no longer support this project as open source.  This issue has been addressed in [Easy Photo Downloader](https://easydownload.photos/).  

For further assistance, please use the feedback mechanisms provided at [Easy Photo Downloader](https://easydownload.photos/).
